package:
  name: bencode2
  version: '0.3.24'

source:
  path: '..'
  use_gitignore: true

build:
  number: 0
  script: >-
    ${{ PYTHON }} -m pip install
    --no-deps --no-build-isolation -vv
    --config-settings=setup-args="-Ddefault_library=shared"
    .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - python
    - pip
    - meson
    - ninja
    - nanobind==2.4.0
    - nanobind-abi
    - meson-python
  host:
    - python
    - pip
    - meson
    - nanobind==2.4.0
    - nanobind-abi
    - ninja
    - meson-python
  run:
    - python
    - typing_extensions>=4.8.0

tests:
  - python:
      imports:
        - bencode2
