package:
  name: bencode2
  version: ${{ env.get("BENCODE2_CONDA_VERSION", default='dev') }}

source:
  path: '..'
  use_gitignore: true

build:
  number: 0
  script: '${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .'

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - c-compiler 1.9.*
    - cxx-compiler 1.9.*
  host:
    - python
    - pip
    - meson
    - ninja
    - meson-python
  run:
    - python
    - typing_extensions>=4.8.0

tests:
  - python:
      imports:
        - bencode2

  - script:
      - pytest tests --assert-pkg-compiled=true

    requirements:
      run:
        - pytest

    files:
      source:
        - tests/
