package:
  name: bencode2
  version: ${{ env.get("BENCODE2_CONDA_VERSION", default='dev') }}

source:
  path: '..'
  use_gitignore: true

build:
  number: 0
  skip: (python_allow_limited_api == 'true') and (win or (python != '3.12'))
  python:
    skip_pyc_compilation: true
    version_independent: ${{ python_allow_limited_api == 'true' }}
  script: >-
    ${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
    --config-settings=setup-args=-Dpython.allow_limited_api=${{ python_allow_limited_api }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - c-compiler >=1.9.0
    - cxx-compiler >=1.9.0
  host:
    - python
    - if: python_allow_limited_api == 'true'
      then:
        - python-abi3 3.12.*
    - pip
    - meson
    - ninja
    - meson-python
  run:
    - if: python_allow_limited_api == 'true'
      then:
        - python >=${{ python }}
      else:
        - python
    - typing_extensions>=4.8.0

  ignore_run_exports:
    from_package:
      - if: python_allow_limited_api == 'true'
        then:
          - python

tests:
  - python:
      imports:
        - bencode2
      python_version:
        - ${{ python }}.*

  - if: python_allow_limited_api == 'true' and unix
    then:
      script:
        - abi3audit -v ${{ SP_DIR }}/bencode2/__bencode.abi3.so --assume-minimum-abi3 ${{ python }}
      requirements:
        run:
          - abi3audit

  - script:
      - pytest tests --assert-pkg-compiled=true

    requirements:
      run:
        - pytest
        - python

    files:
      source:
        - tests/
