from .__bencode import bdecode, bencode

__all__ = ["bencode", "bdecode", "BencodeDecodeError", "BencodeEncodeError", "COMPILED"]

class BencodeDecodeError(ValueError): ...
class BencodeEncodeError(ValueError): ...

COMPILED: bool = ...
