from .__bencode import bdecode, bencode

__all__ = ["COMPILED", "BencodeDecodeError", "BencodeEncodeError", "bdecode", "bencode"]

class BencodeDecodeError(ValueError): ...
class BencodeEncodeError(ValueError): ...

COMPILED: bool = ...
