name: build conda packages

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/renovate.json
      - .pre-commit-config.yaml
      - readme.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/renovate.json
      - .pre-commit-config.yaml
      - readme.md

  # build conda package weekly to see if it's broken
  schedule:
    - cron: "0 3 * * 3"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: windows-latest
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - run: rm C:/Strawberry/perl/bin -rf
        if: ${{ runner.os == 'Windows' }}
        shell: bash

      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ runner.os == 'Windows' }}

      - name: Install rattler-build
        uses: jaxxstorm/action-install-gh-release@v2.0.0
        with:
          repo: prefix-dev/rattler-build
          tag: v0.39.0
        env:
          GITHUB_TOKEN: "${{ github.token }}"

      - name: Install the latest version of uv
        if: ${{ runner.os != 'Linux' }}
        uses: astral-sh/setup-uv@v5

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --output-dir=./output \
            --verbose \
            --recipe=./conda/recipe.yaml
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@v4
        with:
          name: "conda-${{ runner.os }}-${{ runner.arch }}"
          path: ./output/*/*.conda
          if-no-files-found: ignore
