name: build conda packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: windows-latest
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - run: rm C:/Strawberry/perl/bin -rf
        if: ${{ runner.os == 'Windows' }}
        shell: bash

      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ runner.os == 'Windows' }}

      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
          run-install: false

      - run: pixi global install rattler-build

      - name: Install the latest version of uv
        if: ${{ runner.os != 'Linux' }}
        uses: astral-sh/setup-uv@v5

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --output-dir=./output \
            --verbose \
            --recipe=./conda/recipe.yaml
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@v4
        with:
          name: "conda-${{ runner.os }}-${{ runner.arch }}"
          path: ./output/*/*.conda
          if-no-files-found: ignore
